const USER_ROLES = {
  ADMIN: 'ADMIN',
  TEAM: 'TEAM',
  CLIENT: 'CLIENT',
};

const CLIENT_TYPES = {
  INDIVIDUAL: 'INDIVIDUAL',
  COMPANY: 'COMPANY',
  REAL_ESTATE_DEVELOPER: 'REAL_ESTATE_DEVELOPER',
  ARCHITECT: 'ARCHITECT',
  BTP_COMPANY: 'BTP_COMPANY',
  INSTITUTION: 'INSTITUTION',
  PARTICULIER: 'INDIVIDUAL',
  PROFESSIONNEL: 'COMPANY',
  OTHER: 'OTHER',
};

const BUILDING_TYPES = {
  APARTMENT: 'APARTMENT',
  HOUSE: 'HOUSE',
  BUILDING: 'BUILDING',
  OFFICE: 'OFFICE',
  SCHOOL: 'SCHOOL',
  HOSPITAL: 'HOSPITAL',
  HOTEL: 'HOTEL',
  STORE: 'STORE',
  WAREHOUSE: 'WAREHOUSE',
  INSTITUTIONAL: 'INSTITUTIONAL',
  OTHER: 'OTHER',
};

const CONSTRUCTION_STATUS = {
  HEAVY_WORK_DONE: 'HEAVY_WORK_DONE',
  NEARLY_FINISHED: 'NEARLY_FINISHED',
  FINISHED: 'FINISHED',
  IN_PROGRESS: 'IN_PROGRESS',
  NEW_BUILD: 'NEW_BUILD',
};

const DIRT_LEVELS = {
  LIGHT: 'LIGHT',
  MEDIUM: 'MEDIUM',
  HEAVY: 'HEAVY',
  SEVERE: 'SEVERE',
  UNKNOWN: 'UNKNOWN',
};

const QUOTE_REQUEST_STATUS = {
  NEW: 'NEW',
  UNDER_REVIEW: 'UNDER_REVIEW',
  SITE_VISIT: 'SITE_VISIT',
  QUOTE_SENT: 'QUOTE_SENT',
  NEGOTIATION: 'NEGOTIATION',
  ACCEPTED: 'ACCEPTED',
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
};

const APPOINTMENT_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  RESCHEDULED: 'RESCHEDULED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW',
};

const APPOINTMENT_REASONS = {
  SITE_VISIT: 'SITE_VISIT',
  ESTIMATION: 'ESTIMATION',
  PROJECT_DISCUSSION: 'PROJECT_DISCUSSION',
  MONITORING: 'MONITORING',
  OTHER: 'OTHER',
};

const PROJECT_STATUS = {
  PLANNED: 'PLANNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
};

const MEDIA_CATEGORIES = {
  BEFORE: 'BEFORE',
  AFTER: 'AFTER',
  DURING: 'DURING',
  GENERAL: 'GENERAL',
};

const MEDIA_TYPES = {
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
};

module.exports = {
  USER_ROLES,
  CLIENT_TYPES,
  BUILDING_TYPES,
  CONSTRUCTION_STATUS,
  DIRT_LEVELS,
  QUOTE_REQUEST_STATUS,
  APPOINTMENT_STATUS,
  APPOINTMENT_REASONS,
  PROJECT_STATUS,
  MEDIA_CATEGORIES,
  MEDIA_TYPES,
};
